# Generated by Django 3.1.7 on 2021-04-25 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_auto_20210425_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.PositiveSmallIntegerField(max_length=1),
        ),
    ]
