# Generated by Django 3.1.7 on 2021-04-25 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_auto_20210425_1317'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYearModel',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('start_year', models.DateField()),
                ('end_year', models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AddField(
            model_name='student',
            name='academic_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='project.academicyearmodel'),
        ),
    ]
