# Generated by Django 3.1.7 on 2021-04-26 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_auto_20210425_2300'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='academic_id',
        ),
        migrations.DeleteModel(
            name='AcademicYearModel',
        ),
    ]
