# Generated by Django 3.1.7 on 2021-04-27 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0006_auto_20210426_1522'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guide',
            name='department',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='guide',
            name='phone_number',
            field=models.CharField(max_length=50),
        ),
    ]
