# Generated by Django 3.1.7 on 2021-04-27 13:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0009_auto_20210427_1856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='admin',
        ),
        migrations.AddField(
            model_name='student',
            name='admin',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
