# Generated by Django 3.1.7 on 2021-04-27 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_auto_20210427_1912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='team_id',
        ),
        migrations.AlterField(
            model_name='student',
            name='sem',
            field=models.IntegerField(),
        ),
    ]
