# Generated by Django 3.1.7 on 2021-04-27 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0014_auto_20210427_2259'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='enrollment_no',
        ),
    ]
