# Generated by Django 3.1.7 on 2021-04-27 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0015_remove_student_enrollment_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='phon_no',
            field=models.CharField(max_length=12, null=True),
        ),
    ]
