# Generated by Django 3.1.7 on 2021-04-28 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0019_auto_20210428_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment_no',
            field=models.CharField(default='1234567890', max_length=20, unique=True),
        ),
    ]
