# Generated by Django 3.1.7 on 2021-04-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0021_auto_20210428_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hod',
            name='phone_number',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
