# Generated by Django 3.1.7 on 2021-04-29 06:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0022_auto_20210428_1921'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='project_id',
            new_name='p_id',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='project_id',
            new_name='p_id',
        ),
    ]
