# Generated by Django 3.1.7 on 2021-04-29 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0023_auto_20210429_1207'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='leader',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
